name: price_converter
description: Convert price with or without currency & formatter
version: 0.0.1
homepage: https://github.com/Dharini17/price_converter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: 'Price convert demo'
    path: screenshots/screenshot1.png